Test Suite 'Suite' started at {{startDate}}{{#tests}}
Test Case '-[Test {{llamaCase(name)}}]' started.{{#failure}}
{{#isEmpty(filePath)}}Unknown.m{{^}}{{filePath}}{{/}}:{{#isEmpty(lineNumber)}}0{{^}}{{lineNumber}}{{/}}: error: -[Test {{llamaCase(name)}}] : {{reason}}
Test Case '-[Test {{llamaCase(name)}}]' failed (0.001 seconds).{{^failure}}
Test Case '-[Test {{llamaCase(name)}}]' passed ({{threeDecimalPoints(duration)}} seconds).{{/failure}}{{/tests}}
Test Suite 'Suite' finished at {{finishDate}}.
Executed {{tests.count}} {{#pluralize(tests.count)}}test{{/}}, with {{numberOfFailures(tests)}} {{#pluralize(numberOfFailures(tests))}}failure{{/}} (0 unexpected) in {{threeDecimalPoints(duration)}} ({{threeDecimalPoints(duration)}}) seconds